FROM gradle:8.5-jdk17 AS builder
WORKDIR /build

COPY build.gradle settings.gradle ./
COPY gradle ./gradle
RUN gradle --no-daemon build -x test || true

COPY . .

RUN gradle clean build -x test --no-daemon

FROM eclipse-temurin:17-jre-alpine

ENV TZ=Asia/Seoul
ENV LANG=ko_KR.UTF-8

WORKDIR /app

COPY --from=builder /build/build/libs/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "-Duser.timezone=Asia/Seoul", "app.jar"]