-- ==============================
--  POSTGIS EXTENSIONS
-- ==============================
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS postgis_topology;

-- ==============================
--  Region Type
-- ==============================
create table region_type
(
    id        bigint generated by default as identity primary key,
    name      varchar(100) not null constraint uk_region_type_name unique,
    prefix    varchar(20)  not null constraint uk_region_type_prefix unique,
    parent_id bigint constraint fk_region_type_parent_id_region_type references region_type
);

-- ==============================
--  MEMBER
-- ==============================
create table member
(
    id         bigint generated by default as identity primary key,
    created_at timestamp(6),
    updated_at timestamp(6),
    email      varchar(255) not null constraint uk_member_email unique,
    height     double precision,
    is_deleted boolean      not null,
    kakao_id   bigint constraint uk_member_kakao_id unique,
    nickname   varchar(20)  not null,
    password   varchar(255) not null,
    region_cd  varchar(20)  not null,
    role       varchar(20)  not null constraint member_role_check check ((role)::text = ANY ((ARRAY ['STUDENT'::character varying, 'PARENT'::character varying])::text[])),
    school     varchar(100),
    uuid       varchar(50)  not null,
    weight     double precision
);

-- ==============================
--  Parent-Child
-- ==============================
create table parent_child
(
    id        bigint generated by default as identity primary key,
    child_id  bigint not null constraint fk_parent_child_child_id_member references member,
    parent_id bigint not null constraint fk_parent_child_parent_id_member references member
);

-- ==============================
--  FACILITY
-- ==============================
create table facility
(
    id                   bigint generated by default as identity primary key,
    address              varchar(500),
    facility_subtype     varchar(200),
    facility_type        varchar(50)           not null constraint facility_facility_type_check check ((facility_type)::text = ANY ((ARRAY ['BALL_GAME'::character varying, 'MARTIAL_ARTS'::character varying, 'FITNESS'::character varying, 'DANCE'::character varying, 'AQUATIC'::character varying, 'LEISURE'::character varying, 'COMPLEX'::character varying, 'ETC'::character varying])::text[])),
    hmpg_url             varchar(200),
    is_voucher_available boolean,
    latitude             numeric(10, 8)        not null,
    location             geometry(Point, 4326) not null,
    longitude            numeric(11, 8)        not null,
    name                 varchar(100)          not null,
    region_cd            varchar(20)           not null
);

-- ==============================
--  Facility Review
-- ==============================
create table facility_review
(
    id          bigint generated by default as identity primary key,
    content     text,
    rating      integer not null,
    facility_id bigint  not null constraint fk_facility_review_facility references facility,
    member_id   bigint  not null constraint fk_facility_review_member references member
);

-- ==============================
--  Program
-- ==============================
create table program
(
    id               bigint generated by default as identity primary key,
    address          varchar(500)          not null,
    begin_date       date,
    capacity         integer,
    end_date         date,
    end_time         time(6),
    facility_subtype varchar(200),
    facility_type    varchar(50)           not null constraint program_facility_type_check check ((facility_type)::text = ANY ((ARRAY ['BALL_GAME'::character varying, 'MARTIAL_ARTS'::character varying, 'FITNESS'::character varying, 'DANCE'::character varying, 'AQUATIC'::character varying, 'LEISURE'::character varying, 'COMPLEX'::character varying, 'ETC'::character varying])::text[])),
    hmpg_url         varchar(200),
    latitude         numeric(10, 8)        not null,
    location         geometry(Point, 4326) not null,
    longitude        numeric(11, 8)        not null,
    name             varchar(200)          not null,
    price            integer,
    region_cd        varchar(20)           not null,
    start_time       time(6),
    target           integer,
    weekday_number   integer
);

-- ==============================
--  Program Review
-- ==============================
create table program_review
(
    id         bigint generated by default as identity primary key,
    content    text,
    rating     integer not null,
    member_id  bigint  not null constraint fk_program_review_member references member,
    program_id bigint  not null constraint fk_program_review_program references program
);

-- ==============================
--  Member-Facility
-- ==============================
create table member_facility
(
    id          bigint generated by default as identity primary key,
    facility_id bigint not null constraint fk_member_facility_facility references facility,
    member_id   bigint not null constraint fk_member_facility_member references member
);

-- ==============================
--  Member-Program
-- ==============================
create table member_program
(
    id         bigint generated by default as identity primary key,
    member_id  bigint not null constraint fk_member_program_member references member,
    program_id bigint not null constraint fk_member_program_program references program
);

-- ==============================
--  Check in Record
-- ==============================
create table check_in_record
(
    id          bigint generated by default as identity primary key,
    date        date    not null,
    time        time(6) not null,
    type        boolean,
    facility_id bigint  not null constraint fk_check_in_record_facility references facility,
    member_id   bigint  not null constraint fk_check_in_record_member references member
);

-- ==============================
--  Steps Record
-- ==============================
create table steps_record
(
    id        bigint generated by default as identity primary key,
    count     integer,
    date      date   not null,
    distance  double precision,
    member_id bigint not null constraint fk_steps_record_member references member,
    constraint uk_steps_record_member_date unique (member_id, date)
);

-- ==============================
--  Self Record
-- ==============================
create table self_record
(
    id            bigint generated by default as identity primary key,
    date          date        not null,
    duration      interval    not null,
    exercise_type varchar(50) not null constraint self_record_exercise_type_check check ((exercise_type)::text = ANY ((ARRAY ['BALL_GAME'::character varying, 'MARTIAL_ARTS'::character varying, 'FITNESS'::character varying, 'DANCE'::character varying, 'AQUATIC'::character varying, 'LEISURE'::character varying, 'COMPLEX'::character varying, 'ETC'::character varying])::text[])),
    member_id     bigint      not null constraint fk_self_record_member references member
);

-- ==============================
--  Member Score
-- ==============================
create table member_score
(
    id            bigint generated by default as identity primary key,
    created_at    timestamp(6),
    updated_at    timestamp(6),
    checkin_score integer,
    date          date   not null,
    self_score    integer,
    steps_score   integer,
    total_score   integer GENERATED ALWAYS AS (steps_score * 0.2 + checkin_score + self_score) STORED,
    member_id     bigint not null constraint fk_member_score_member references member,
    constraint uk_member_score_member_date unique (member_id, date)
);

-- ==============================
--  Daily Region Score
-- ==============================
create table daily_region_score
(
    id         bigint generated by default as identity primary key,
    created_at timestamp(6),
    updated_at timestamp(6),
    date       date   not null,
    score      integer,
    region_id  bigint not null constraint fk_daily_region_score_region_type references region_type,
    constraint uk_daily_region_score_region_date unique (region_id, date)
);

-- ==============================
--  Weekly Region Score
-- ==============================
create table weekly_region_score
(
    id          bigint generated by default as identity primary key,
    created_at  timestamp(6),
    updated_at  timestamp(6),
    month       integer,
    score       integer,
    week_number integer,
    year        integer,
    region_id   bigint not null constraint fk_weekly_region_score_region_type references region_type
);

-- ==============================
--  League Status
-- ==============================
create table league_status
(
    id         bigint generated by default as identity primary key,
    created_at timestamp(6),
    updated_at timestamp(6),
    type       varchar(50) not null constraint league_status_type_check check ((type)::text = ANY ((ARRAY ['START'::character varying, 'WALK'::character varying, 'RUN'::character varying, 'ADVENTURE'::character varying, 'CHAMPION'::character varying])::text[])),
    region_id  bigint      not null constraint fk_league_status_region_type references region_type
);