CREATE TABLE notification
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    member_id       BIGINT                                  NOT NULL,
    fcm_token       VARCHAR(500)                            NOT NULL,
    device_type     VARCHAR(20)                             NOT NULL,
    device_id       VARCHAR(100),
    is_push_enabled BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_notification PRIMARY KEY (id)
);

ALTER TABLE notification
    ADD CONSTRAINT FK_NOTIFICATION_ON_MEMBER FOREIGN KEY (member_id) REFERENCES member (id);

CREATE INDEX idx_notification_member ON notification (member_id);
CREATE INDEX idx_notification_fcm_token ON notification (fcm_token);