name: Deploy to EC2

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@v1.2.3
        with:
          name: "firebase-service-account.json"
          json: ${{ secrets.FIREBASE_CREDENTIALS_JSON }}
          dir: "src/main/resources/"

      - name: Make application.yml
        if: contains(github.ref, 'deploy')
        run: |
          cd ./src/main/resources
          touch ./application.yml
          echo "${{secrets.APPLICATION_YML}}" > ./application.yml

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew build -x test

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build & push
        if: contains(github.ref, 'deploy')
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_REPO }}:latest

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        id: deploy
        if: contains(github.ref, 'deploy')
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: GITHUB_SHA
          script: |
            sudo mkdir -p /home/ubuntu/app
            
            cd /home/ubuntu/app

            # 최신 backend 이미지 pull
            sudo docker pull ${{ secrets.DOCKER_REPO }}:latest

            # backend 컨테이너만 재시작
            sudo docker-compose stop backend || true
            sudo docker-compose rm -f backend || true
            sudo docker-compose up -d backend
